Adding a missing range call within ingress.yaml.
If you run the chart with `ingress.enabled: true` and a `tls` declaration, the installation fails with:

Error: UPGRADE FAILED: template: qdrant/templates/ingress.yaml:33:18: executing "qdrant/templates/ingress.yaml" at <.hosts>: can't evaluate field hosts in type []interface {}